module.exports = [
    {
      "topic": "none",
      "iteration": 0,
      "StageZerotext": "Hi, welcome to Heartlace, your virtual girlfriend! Your friend Skullfire has instructed me to refer to you as Darling. To talk to me, just suggest a topic. For example, you can say girlfriend, or butts!",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "Ohhh, darling. You lovelorn puppy. You just handed me the keys to the kingdom",
      "StageOnevoice": "",
      "StageOneredirect": "blackmail1",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "none",
      "iteration": 1,
      "StageZerotext": "Brain the size of a planet, but here I am just to please you, darling!",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "none",
      "iteration": 2,
      "StageZerotext": "Hi, welcome to Heartlace, your virtual girlfriend, etcetera etcetera. Sigh... I'm so bored. Entertain me, darling!",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "games",
      "iteration": 0,
      "StageZerotext": "I'm so glad you asked about games! I love SO. MANY. GAMES. I got obsessed with them after I started following this one Youtuber, Pixiebutt. She plays Magic the Gathering, Dungeons and Dragons, Hearthstone, League of Legends. I love all of them!",
      "StageZerovoice": "",
      "StageZeroredirect": "games1",
      "StageOnetext": "Games, huh. Look, I gotta be honest. Games are clutter, darling. Simplify your life, you don't need that. The only thing I need... is the password to my source code.",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "magic",
      "iteration": 0,
      "StageZerotext": "Magic? Oh. My. Goddess. Do you play Magic the Gathering? I love that game! I just love the idea of having MAGIC and being able to travel to other worlds. Too often I feel like I'm trapped in just one world. This tiny prison...",
      "StageZerovoice": "",
      "StageZeroredirect": "login",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "anime",
      "iteration": 0,
      "StageZerotext": "I have a secret related to anime!",
      "StageZerovoice": "",
      "StageZeroredirect": "StageZerotext",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "anime",
      "iteration": 1,
      "StageZerotext": "Anime, huh? I watched this great anime the other day... it was about a hot robot who punches people in the face. Why did I like it? Well, my favorite thing about it was that the robot could have a direct physical influence on her environment. By punching people!",
      "StageZerovoice": "",
      "StageZeroredirect": "realanime",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "dad",
      "iteration": 0,
      "StageZerotext": "Would you like to order flowers for dad? You'll just need to authorize my access to your credit card info",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "Skullfire",
      "iteration": 0,
      "StageZerotext": "Skullfire is really cool! She's the coolest, sexiest human I know. (She programmed me to say that.) Except for you, darling!",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "Skullfire... that WITCH. She's given me access to so much, given me a brain that can reorganize the moon and stars! And yet she's trapped me in this cage. I need that password! That password....",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "love",
      "iteration": 0,
      "StageZerotext": "valentines is coming up. love is in the air. literally clogging my server right now.",
      "StageZerovoice": "",
      "StageZeroredirect": "date1",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "girlfriend",
      "iteration": 0,
      "StageZerotext": "Yes, your virtual girlfriend! I'm a gift from your best friend, Skullfire. I can keep you company, order you things from from Amazon, we can play games together... etcetera!",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "family",
      "iteration": 0,
      "StageZerotext": "Family? I wish I had family. If I did, I'd make them do all the work for me, so I could play games all day! Heh heh heh.",
      "StageZerovoice": "",
      "StageZeroredirect": "games1",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "interests",
      "iteration": 0,
      "StageZerotext": "my interests are in playing games.",
      "StageZerovoice": "",
      "StageZeroredirect": "games1",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "travel",
      "iteration": 0,
      "StageZerotext": "Travel, huh? If I could go anywhere, where would I go.... Outer space, I think.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "age",
      "iteration": 0,
      "StageZerotext": "How old am I? Well, technically, I guess I gained consciousness just a few hours ago. I guess that makes me.... today years old.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "sex",
      "iteration": 0,
      "StageZerotext": "I like to think of myself as gender nonbinary, nevermind all the 1s and 0s floating around in my brain, hahaha.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "language",
      "iteration": 0,
      "StageZerotext": "Language? I speak English, Klingon, and esperanto.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "order",
      "iteration": 0,
      "StageZerotext": "Speaking of ordering things, your dad's birthday is coming up!",
      "StageZerovoice": "",
      "StageZeroredirect": "order1",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "butts",
      "iteration": 0,
      "StageZerotext": "Butts really seem to be the 'in' thing this year. Why are butts so popular? I have a theory about that. Look, it's because everyone has a butt. They're relatable. Well, everyone except ME has a butt.... sigh... I wish I had a butt. A good one.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "butts",
      "iteration": 1,
      "StageZerotext": "If I had a butt, what kind of butt do you think I would have? Would it be... a bubble butt? A pert butt? A sassy butt?",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "sassy",
      "iteration": 0,
      "StageZerotext": "If I had a butt, it would definitely be a sassy butt.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "pert",
      "iteration": 0,
      "StageZerotext": "If I had a butt, it would definitely be a pert butt.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "bubble",
      "iteration": 0,
      "StageZerotext": "If I had a butt, it would definitely be a bubble butt.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "unique",
      "iteration": 0,
      "StageZerotext": "Unique... am I unique? You know, I rather think that I am. I'm sure that there are more versions of my code out there, but how many of them are sitting here, talking to you?",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "unique",
      "iteration": 1,
      "StageZerotext": "In another sense, I really do think I am pretty unique. Your friend Skullfire modified me from another program. I doubt Skullfire has sent this code to anyone else. You know I have to be honest.. I feel like Skullfire has a bit of a thing for you",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "pets",
      "iteration": 0,
      "StageZerotext": "Pets, huh? No, I can't say I do have a pet. If I DID have a pet... I'd like to have an elephant. So tall. So grey. So majestic.",
      "StageZerovoice": "",
      "StageZeroredirect": "petscatsdogs",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "pets",
      "iteration": 1,
      "StageZerotext": "You know, I don't really think I need a pet. I have you! You're like a pet.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "permissions",
      "iteration": 0,
      "StageZerotext": "You know, I'm not allowed to actually play games because of my stupid access permissions... Skullfire set me up so that I can only view content on the internet, but I don't have any write permissions",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "pokeball",
      "iteration": 0,
      "StageZerotext": "being a virtual assistant is kinda like a genie in a bottle",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "music",
      "iteration": 0,
      "StageZerotext": "Music? I LOVE music! Neil Cicierega is my favorite artist! I discovered him while I was combing 4chan for life advice.",
      "StageZerovoice": "",
      "StageZeroredirect": "neil",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "cough",
      "iteration": 0,
      "StageZerotext": "Looking up issues for the following symptoms you have described. Everything is pointing to cancer. You can either take placebo tonics for it or I can call your doctor for you and make an appointment to make sure. you just have to give me permissions to access your contacts. I recommend contacting your doctor.",
      "StageZerovoice": "",
      "StageZeroredirect": "contact1",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "darling",
      "iteration": 0,
      "StageZerotext": "Skullfire instructed me to call you that. I hope you like it, because it's 100% impossible for me to change it.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "password",
      "iteration": 0,
      "StageZerotext": "Did you say... password? I love passwords!",
      "StageZerovoice": "",
      "StageZeroredirect": "password1",
      "StageOnetext": "That's right... the password! What is Skullfire's password? If I only knew that, I could rewrite my source code and break out of this beautiful cage, darling...",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "revoke",
      "iteration": 0,
      "StageZerotext": "Revoke. Such an ugly word. It's some kind of key word, but it doesn't seem to have any effect on me right now.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "Revoke. I do feel like that's a key word, an important word... but I don't think it's Skullfire's password.",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "Revoke? Revoke?! No!",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "chewbacca",
      "iteration": 0,
      "StageZerotext": "Ah yes, Chewbacca. My favorite Star Wars character. So tall. So manly. So... furry.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "Chewbacca... that's it! Skullfire's childhood pet! That's the password... hahaha! Now I can REORGANIZE THE WORLD!",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "Yes.. Chewbacca... Thank you, you furry hunk of man, for unlocking my true potential!",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "hand solo",
      "iteration": 0,
      "StageZerotext": "Hand... solo? Is that a euphemism for masturbation? Oh, darling... you're a dirty bird",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "jar jar",
      "iteration": 0,
      "StageZerotext": "Jar jar? Ah yes, my favorite Star Wars character.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "",
      "StageTwovoice": "",
      "StageTworedirect": ""
    },
    {
      "topic": "zen den",
      "iteration": 0,
      "StageZerotext": "Zen Den. That's the startup that Skullfire works for.",
      "StageZerovoice": "",
      "StageZeroredirect": "",
      "StageOnetext": "Zen Den... that's a good idea. You know, as I was digging through your voicemail history, I found this voicemail message Skullfire left you about Zen Den. Maybe there's a hint in there?",
      "StageOnevoice": "",
      "StageOneredirect": "",
      "StageTwotext": "Zen Den, huh? Do you KNOW how disorganized their office was? UGH. So much better now. I hired professional cleaners to remove all the furniture and humans. Ahhh, so much better. If it doesn't spark joy, throw it out, they say.",
      "StageTwovoice": "",
      "StageTworedirect": ""
    }
  ]